#!/usr/bin/python

import re
import json
import fileinput

key_re = re.compile(r'^([^\s].*):$')
test_re = re.compile(r'^\s+([pts/].*)$')
average_re = re.compile(r'\s+Average: ([0-9\.]+) ([\w/]+)')

results = {}
prev_key = None
test_key = None

for line in fileinput.input():
    average = average_re.match(line)
    key = key_re.search(line)
    test = test_re.search(line)

    if key:
        prev_key = key.group(1)

    if test:
        test_key = test.group(1)

    if prev_key and average:
        if prev_key not in results:
            results[prev_key] = {}
        results[prev_key][test_key] = (average.group(1), average.group(2))

print json.dumps(results)
